### ISSUE TITLE
Editor for property "openInNewTab" not configured

### ISSUE THREAD

**Issue by kdambekalns** [neos/Neos.NeosIo#194] opened 2018-01-24 10:40 UTC
When selecting an image an error is raised:

`Couldn't create editor for property "openInNewTab" (no editor configured). Please check your NodeTypes.yaml configuration.`

**Comment by Sebobo** [comment] 2018-06-29 10:02
@kdambekalns I cannot reproduce this. 
The property comes from `Neos.NodeTypes:LinkMixin` and there it's fully defined.
Maybe this has been resolved in another change in the last months.

**Closed** 2019-05-15 09:47 UTC
Labels: bug
